apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginxdeployment
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxdeployment
    spec:
      serviceAccountName: mikeuser
      containers:
      - name: nginxdeployment
        image: nginx:latest
        ports:
        - containerPort: 80