apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: orders-vertical
  namespace: sock-shop
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: orders
  updatePolicy:
    updateMode: "Auto"